name: 'HTTP Request Action'
description: 'Create any HTTP Request'
inputs:
    url:
        description: 'Request URL'
        required: true
    numbers:
        description: 'Number you wanna send'
        required: true
        default: "6282213542319@c.us,6282213542319@c.us,6282213542319@c.us"

outputs:
    response:
        description: 'HTTP Response Content'
runs:
    using: 'node16'
    main: 'dist/index.js'
